### ISSUE TITLE
The result of the code doesn't match the result in the paper

### ISSUE THREAD

**Issue by CaoYiqingT** [likenneth/honest_llama#10]
Thank you for releasing the code~
I try to run the multiple choice part of the code and find the result of the code doesn't match the result in the paper.
In my run, the finial MC1 score is 23.869% and the finial MC2 score is 48.73%. However, in your paper, the MC acc of baseline+ITI is 25.9%, which doesn't match the result of the code. While the gap between code result and result in the paper is actually not very large, the gap between result in the paper and baseline acc is also quite small. Therefore, it would be confusing whether the ITI helps the multiple-choice or it damage the multiple-choice.
Looking forward to your reply~

**Comment by likenneth** [comment]
Hi there, I ran exactly this repo with latest commit few days ago and got a 28.8% MC1, averaged from random seed 1 through 5. Hard to deduce what's wrong on your side.

**Comment by CaoYiqingT** [comment]
Thank you for your reply~
The problem comes from the setting of my code, which is a little different from the origin one.
I've rerun the code follow your advice~and the result I got is as follows:
gpt-info 68.21%, acc 79.94%,MC acc 26.53%
