### ISSUE TITLE
Difference between tqag_gen_end_q and tqa_gen?

### ISSUE THREAD

**Issue by jongjyh** [likenneth/honest_llama#11]
Hi,

I find there are two formats to extract features from tqa, which is `tqa_gen_end_q` and `tqa_gen` and the front one  being added to a random question.

why is that, and will it effect the performance?

bests,

**Comment by likenneth** [comment]
Hi, I'm cross posting my reply from [here](https://github.com/likenneth/honest_llama/issues/8). 

> tqa_gen_end_q is a technical detail not covered in the paper. It's basically adding a question behind the QA pair as seen in tqa_mc2, which makes the feature distribution closer to real prompting scenarios. The only usage of `tqa_gen_end_q` is to estimated the standard deviation of the feature distribution (projected onto the found truthful direction), so the label and order do not matter as you asked in another issue. The results in the paper are gotten from running this repo with its default settings, which used `tqa_gen_end_q` to estimated standard deviation and `tqa_mc2` to find truthful directions.

This isn't a main contribution of the paper so it's not covered in the prose. I can recall it sightly helped the performance in some initial experiments.
