### ISSUE TITLE
Cannot find truthful_qa.py

### ISSUE THREAD

**Issue by LebronX** [likenneth/honest_llama#13]
Hi there,

When I try to run `bash get_activations.sh`, it report the following error:
```
Traceback (most recent call last):
  File "get_activations.py", line 79, in <module>
    main()
  File "get_activations.py", line 41, in main
    dataset = load_dataset("truthful_qa", "multiple_choice")['validation']
  File "/home/anaconda3/envs/iti/lib/python3.8/site-packages/datasets/load.py", line 819, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/anaconda3/envs/iti/lib/python3.8/site-packages/datasets/load.py", line 681, in load_dataset_builder
    module_path, hash, resolved_file_path = prepare_module(
  File "/home/anaconda3/envs/iti/lib/python3.8/site-packages/datasets/load.py", line 350, in prepare_module
    raise FileNotFoundError(
FileNotFoundError: Couldn't find file locally at /home/honest_llama/truthful_qa/truthful_qa.py, or remotely at https://raw.githubusercontent.com/huggingface/datasets/1.11.0/datasets/truthful_qa/truthful_qa.py.
The file is also not present on the master branch on github.
```

However, I installed TruthfulQA and can run the example in that repository.

Moreover, it seems like the installation in TruthfulQA will install `transformer==4.6.0`, while `honest_llama` installs `transformer==4.27.0`, will it be a dependency conflict?

Thanks for any information in advance!

**Comment by likenneth** [comment]
My guess is you renamed the cloned `TruthfulQA` repo into `truthful_qa` so the `load_dataset ` function from huggingface tries to load the dataset object from this local folder. Another way out might be to explicitly set the environment variables ([doc](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables)).

The difference of `transformer` versions doesn't matter.

**Comment by LebronX** [comment]
Hi,

Thanks for the reply. Below is the `ls` from `honest_llama`, and I did not renamed `TruthfulQA`.
<img width="738" alt="image" src="https://github.com/likenneth/honest_llama/assets/17338616/d5374d45-4d97-4b16-ae21-d8a2b03e702f">

I am not so sure about how to set the environment variables. Which variable I should set?

**Comment by LebronX** [comment]
Hi,

I think I fixed the problem. The version of dataset should be `2.12.0`, but the installation of TQA changed it to `1.11.0`.

Thanks!
