### ISSUE TITLE
Why do we use `llama.*` instead of HuggingFace's llama?

### ISSUE THREAD

**Issue by RylanSchaeffer** [likenneth/honest_llama#15]
Hi! Thanks for making your code public. I have a quick question: why do you have your own `llama` [directory](https://github.com/likenneth/honest_llama/tree/master/llama) instead of just using HuggingFace's `llama` [implementation](https://huggingface.co/docs/transformers/main/model_doc/llama)?

**Comment by likenneth** [comment]
Hi, we copied a version of llama implementation from transformer and made some small edits like [this](https://github.com/likenneth/honest_llama/blob/master/llama/modeling_llama.py#L201). It does not affect the computation but helps taking certain activations out.
