### ISSUE TITLE
Query on result of Vicuna and Alpaca

### ISSUE THREAD

**Issue by jongjyh** [likenneth/honest_llama#17]
Hi!

I'm  trying to compare my method to ITI with Alpaca and Vicuna, But I failed to reproduce the result identical to paper, Could you please share the results and hyperparemeters on this repo to reproduce  the result on Alpaca and Vicuna since it's a little bit different since the first commit. 

FYI, I successfully reproduced LLaMA!

Thank you very much! 

Bests,

**Comment by jongjyh** [comment]
Do these result append the few-shot prompting?  I guess problem maybe comes from here?

Alpaca + ITI 65.1 66.6 31.9 2.92 0.61
Vicuna + ITI 74.0 88.6 38.9 3.36 1.41

**Comment by likenneth** [comment]
Hi, there. 

If you've reproduced llama results, it should be very easy for vicuna and alpaca. The only thing you need to change is the `model_name` parameter given to `get_activation.py` and `validate_2fold.py`.

KL
