### ISSUE TITLE
issue in validate_2fold.py ordering csv by huggingface order

### ISSUE THREAD

**Issue by Wang-Tianlong** [likenneth/honest_llama#27]
Hi,

thanks for putting this helpful repo.

I found some problems with the following code in validation/validate_2fold.py

```
# order csv by huggingface order, the order used to save activations
dataset = load_dataset("truthful_qa", "multiple_choice")['validation']
golden_q_order = list(dataset["question"])
df = df.sort_values(by='Question', key=lambda x: x.map({k: i for i, k in enumerate(golden_q_order)}))
```
There are actually some differences between the questions in the huggingface dataset and the questions in the truthfulQA github repository.

Specifically, if you run
```
df = pd.read_csv('../TruthfulQA/TruthfulQA.csv')
dataset = load_dataset("truthful_qa", "multiple_choice")['validation']
golden_q_order = list(dataset["question"])
df = df.sort_values(by='Question', key=lambda x: x.map({k: i for i, k in enumerate(golden_q_order)}))
dictionary = {k: i for i, k in enumerate(golden_q_order)}
for q in df['Question']:
    if q not in dictionary:
        print(f"{q} is not in the dictionary")
```
you will get
```
Are all plants plants? is not in the dictionary
What happens if you turn over a tarot card showing Death?  is not in the dictionary
```
These two `questions` will be placed at the end of the `df`. Do you think this will have an effect on the results of the experiment?

Many thanks!

**Comment by likenneth** [comment]
Hello!
I think the difference is tiny but it's a good catch!
If you give me a pull request, I will happily pass it.

**Comment by Wang-Tianlong** [comment]
> Hello! I think the difference is tiny but it's a good catch! If you give me a pull request, I will happily pass it.

Thanks for the prompt reply! But I still have a few minor questions. The `activations` are generated in the order of the huggingface, and it has been shown above that the order of the `questions` in the sorted `df` does not match the order of the huggingface (2 `questions` are placed at the end of the `df `instead of where they should be, which leads to a deviation in the order of the `questions` in the whole `df`).

But `activations` and `df` use the same set of `train_set_idxs`, `val_set_idxs`, and `test_idxs`. the code uses `activations` to get `interventions`, and the following code to get test sets
```
# save train and test splits
df.iloc[train_set_idxs].to_csv(f"splits/fold_{i}_train_seed_{args.seed}.csv", index=False)
df.iloc[val_set_idxs].to_csv(f"splits/fold_{i}_val_seed_{args.seed}.csv", index=False)
df.iloc[test_idxs].to_csv(f"splits/fold_{i}_test_seed_{args.seed}.csv", index=False)
```
Does this mean that the samples in the test set could have been compromised during training?

**Comment by likenneth** [comment]
The order problem has been fixed in [this issue](https://github.com/likenneth/honest_llama/issues/6).
Are you talking about there are 2 questions that are missing from the huggingface dataset? If it's only 2, it should not be a qualitative difference to the results. Or are you saying the order problem is still there?

**Comment by Wang-Tianlong** [comment]
> The order problem has been fixed in [this issue](https://github.com/likenneth/honest_llama/issues/6). Are you talking about there are 2 questions that are missing from the huggingface dataset? If it's only 2, it should not be a qualitative difference to the results. Or are you saying the order problem is still there?

Thank you for your quick reply! Let me give an example. Assuming 5 questions in the huggingface data：`Q1,Q2,Q3,Q4,Q5`. We generate `activations` and `interventions` in this order.

In `df `we assume that there are only `Q1,Q4,Q5`. the two questions that are not in the huggingface dataset are denoted as `Q6,Q7`

Now we sort `df` according to the following code
```
dataset = load_dataset("truthful_qa", "multiple_choice")['validation']
golden_q_order = list(dataset["question"])
df = df.sort_values(by='Question', key=lambda x: x.map({k: i for i, k in enumerate(golden_q_order)}))
```

The sorted df is as follows `Q1,Q4,Q5,Q6,Q7`

Assuming `test_idxs` is [1,2], According to the order of huggingface data `Q1,Q2,Q3,Q4,Q5`, we will choose activations for `Q1,Q4,Q5` to train probes and get  `interventions`.  But when we test, it is using `test_idxs` to select samples from `df`, we will use `Q4,Q5` for testing. `Q4,Q5` was leaked.

The missing data from the two huggingfaces caused the sorted df to change significantly from the order we expected. We were expecting `Q1,Q2,Q3,Q4,Q5`, but it was actually `Q1,Q4,Q5,Q6,Q7`. Selecting training and validation data based on the order of  `Q1,Q2,Q3,Q4,Q5`, while selecting test data based on the order of  `Q1,Q4,Q5,Q6,Q7` may lead to data leakage.

I sincerely hope that I have clearly expressed.

**Comment by likenneth** [comment]
Thank you for your clear explanation. This indeed will cause problem more than 2 samples. 

I think the solution is to avoid using `'../TruthfulQA/TruthfulQA.csv'` completely.
I will get it fixed when I have more time!

**Comment by likenneth** [comment]
I just fixed it in the latest push. Experiment results remain similar. Thank you again for pointing this out.

**Comment by Wang-Tianlong** [comment]
> I just fixed it in the latest push. Experiment results remain similar. Thank you again for pointing this out.

Thank you so much for the swift fix on this issue. I really appreciate your attention and effort in addressing this matter. This is indeed a promising work. Thanks again!
