### ISSUE TITLE
inquery on equaltion of paper

### ISSUE THREAD

**Issue by jongjyh** [likenneth/honest_llama#3]
Hi,

excellent work! I'd like to ask the intuition of equation of ITI (i.e equation(2) on paper). Does this have any connection with [PPLM](http://arxiv.org/abs/1912.02164) where updates the hidden state accoding to its score( gradient of log likelihood)? why it uses $\sigma*\theta$ to update? I couldn't find explicit explaination on paper.

Also, does ITI need iterative updation like PPLM? 

Thanks in advance. :)

**Comment by likenneth** [comment]
Hi, 

Both PPLM and ITI are working on the innate representation space. However, PPLM gets its gradient from SGD on the text space with a text classifier; and ITI has a learnt and fixed direction $\theta$ for this. 

$\theta$ is normalized to be in a unit sphere, therefore we use $\alpha$ to calibrate the strength of such interventions. 

Unlike PPLM, ITI is one-pass update.
