### ISSUE TITLE
Query regarding dimensions of activations

### ISSUE THREAD

**Issue by itsmemala** [likenneth/honest_llama#32]
Hi,

When I print the dimensions of `head_wise_hidden_states` in `get_llama_activation_bau()`, I see `(32, 21, 4096)`. I see that in `get_activations.py` you then only save the last value of the 21: `all_head_wise_activations.append(head_wise_activations[:,-1,:])`. 

I'm guessing 21 is the number of tokens in the prompt?

**Comment by likenneth** [comment]
Yes, you are right!
