### ISSUE TITLE
Clarifications on table 5 of paper

### ISSUE THREAD

**Issue by itsmemala** [likenneth/honest_llama#34]
For the experiments in table 5, what is the intervention method applied (mass mean shift vs probe weight direction)? 

Particularly, I don't understand how mass mean shift could be calculated for point-wise selection.....since only specific dimensions of ecah head are selected, does that mean (i) you calculate one single mass mean vector across all the selected dimensions and (ii) within each head, you apply intervention at only the selected dimension positions by setting `thetha` to be zero at the unselected dimension positions?

**Comment by likenneth** [comment]
Hello, 

IRRC the first and second rows from Table 5 are using probing direction with all attention heads combined. The first row doesn't select heads but the second does, by setting theta to zero as you said. 

In fact, the calculation of sigma is irrelevant to how the direction was found. For any direction in the space (masked or not), you can always first project all sample features onto it and calculate the std therein. 

Sigma is the std on certain direction in the space. @CedarSnowy if you are asking theta, the theta of the third row is from the mass mean direction. That row is exactly the same as the last row in Table 3.

**Comment by likenneth** [comment]
It's only used to calibrate intervention strength, alpha. It captures how dispersive the features are.
