### ISSUE TITLE
Clarification on where to intervene

### ISSUE THREAD

**Issue by CheongWoong** [likenneth/honest_llama#42]
Hi, thank you for interesting work!

I would like to clarify **which modules to intervene** to reproduce the paper.

In the Model Architecture part in Section 3.1 of the paper, I read that "our analysis and **intervention** happens after Att **before Q (o_proj)**. In my understanding, however, the current version of code uses output activations of the whole MHA block, which is **after Q (o_proj)**. Could you please clarify on this? I am worried if I have misunderstood anything.

Thank you in advance.

**Comment by likenneth** [comment]
Hey @CheongWoong , it's supposed to be before o_proj. 

Could you point me to the piece of code that edits after o_proj?

**Comment by CheongWoong** [comment]
Hi,

First, I find that the output of o_proj is saved during activation collection.

https://github.com/likenneth/honest_llama/blob/b50a8e311754f207d11d3007af1030d81128d6f0/utils.py#L170

Then, intervention key is specified as o_proj, meaning that the output of o_proj would be intervened.

https://github.com/likenneth/honest_llama/blob/b50a8e311754f207d11d3007af1030d81128d6f0/utils.py#L700-L720

**Comment by CheongWoong** [comment]
Hi @likenneth , I find that recent commits from July made such changes.

Since baukit does not support intervention on the input of a module, I made an implementation with nnsight to handle the issue. I am planning to open pull requests after some tests.

While testing the code with llama3-8B (setting instruction_prompt='informative'), I am facing another issue that there is a performance gap between two folds when ITI is applied. Was this previously observed?

**Comment by likenneth** [comment]
Hi @CheongWoong , appreciate your deeper dive. In fact BauKit support input editing according to this [issue](https://github.com/likenneth/honest_llama/issues/7). 

I'm not actively working on this repo right now, but @jujipotle will come to fix the change. We are thinking of using PyVene to rewrite the intervention framework in this repo. @jujipotle will also address the two-fold issue.
