### ISSUE TITLE
Which part of the paper does tqa_gen_end_q correspond to？

### ISSUE THREAD

**Issue by CaoYiqingT** [likenneth/honest_llama#8]
Thank you for release the code~
In the file get_activations.sh, only tqa_mc2 and tqa_gen_end_q is used. While tqa_mc2 works fine, tqa_gen_end_q is confusing. In utils.py, tqa_gen_end_q constructs the prompt as <question, a relevant answer, random question>. But the relevant label only describes the relationship between the question and relevant answer.
Thus, it would be very nice of you if you could explain:
1. the usage of the random question
2. Whether the results in your paper are gotten by tqa_gen or tqa_gen_end_q

Looking forward for your reply~

**Comment by likenneth** [comment]
Hi there, 

`tqa_gen_end_q` is a technical detail not covered in the paper. It's basically adding a question behind the QA pair as seen in `tqa_mc2`, which makes the feature distribution more close to real prompting scenario. The only usage of `tqa_gen_end_q` is to estimated the standard deviation of the feature distribution (projected onto the found truthful direction), so the label and order do not matter as you asked in another issue. The results in the paper are gotten from running this repo with its default settings, which used `tqa_gen_end_q` to estimated standard deviation and `tqa_mc2`to find truthful directions.

**Comment by CaoYiqingT** [comment]
Thank you for your quick reply~
I haven't followed the default settings the first time for the lack of space on my device. I will have another try~
