### ISSUE TITLE
How to use tqa_gen and tqa_end_end_q?

### ISSUE THREAD

**Issue by CaoYiqingT** [likenneth/honest_llama#9]
Although in get_activations.sh, both tqa_mc2 and tqa_gen_end_q is supported, validate_2flod.py seems to force the user to use tqa_mc2. 
The problem comes from the get_separated_arcivations function in utils.py. In get_separated_arcivations function, head_wise_activations is separated by labels, which comes from multiple_choice part of truthful_qa. However, the tqa_gen_end_q activations fails to match the multiple_choice labels. As a result, if get_separated_activations function, assert error appears when operating "assert separated_labels == actual_labels".
Moreover, this problem actually comes from the truthful_qa dataset. As the data in generation part and multiple choice part have different sorting. Even if in the same quesiton, choices in multiple choice and choices in correct_answers/incorrect_answers of multiple choice have different sorting.

**Comment by likenneth** [comment]
Hi, please see answer to your issue 1/3.

**Comment by CaoYiqingT** [comment]
Got it! It's so nice of you! Thanks a lot~
